"""Updating Table User

Revision ID: 45173b81873d
Revises: fb14f7ffe809
Create Date: 2020-03-20 22:20:57.897160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45173b81873d'
down_revision = 'fb14f7ffe809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
