"""Updating Table Playlist

Revision ID: 71a797de0ca6
Revises: 45173b81873d
Create Date: 2020-03-20 23:07:36.077820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a797de0ca6'
down_revision = '45173b81873d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('playlist_title', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=15), nullable=False),
    sa.Column('emotion', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('playlist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist')
    # ### end Alembic commands ###
