"""adding table again

Revision ID: 7f05bf2657d9
Revises: e9709bd9ecb7
Create Date: 2020-03-20 20:07:55.677173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f05bf2657d9'
down_revision = 'e9709bd9ecb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Playlist_id', sa.INTEGER(), nullable=False),
    sa.Column('Track_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
