"""adding table again

Revision ID: bb56c8e3484d
Revises: ae92e4d18a37
Create Date: 2020-03-20 20:06:11.721218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb56c8e3484d'
down_revision = 'ae92e4d18a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_group', sa.Column('playlist_id', sa.Integer(), nullable=False))
    op.add_column('track_group', sa.Column('tg_id', sa.Integer(), nullable=False))
    op.add_column('track_group', sa.Column('track_id', sa.Integer(), nullable=False))
    op.drop_column('track_group', 'id')
    op.drop_column('track_group', 'Playlist_id')
    op.drop_column('track_group', 'Track_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_group', sa.Column('Track_id', sa.INTEGER(), nullable=False))
    op.add_column('track_group', sa.Column('Playlist_id', sa.INTEGER(), nullable=False))
    op.add_column('track_group', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('track_group', 'track_id')
    op.drop_column('track_group', 'tg_id')
    op.drop_column('track_group', 'playlist_id')
    # ### end Alembic commands ###
