"""adding TrackGroup

Revision ID: fb14f7ffe809
Revises: 7f05bf2657d9
Create Date: 2020-03-20 20:11:15.511872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb14f7ffe809'
down_revision = '7f05bf2657d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_group',
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_group')
    # ### end Alembic commands ###
